config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "boards#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :boards do
  resources :lists

end

resources :lists do
  resources :tasks
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :boards

        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show,:update,:edit,:destroy]
 
  def index
  @boards = current_user.boards
  end

  def show
    @lists = @board.lists
  end

  def new
  @board = Board.new
  end

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end
    
    def update
      if @board.update(board_params)
        redirect_to boards_path
      else
        render :edit
      end
    end
    
    def destroy
      @board.destroy
      redirect_to boards_path
    end
    
    private

    def set_board
      @board = current_user.boards.find(params[:id])
    end
  
    def board_params
      params.require(:board).permit(:name)
    end
  end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @tasks = @lists.tasks
  end

  def new
    @board = Board.find(params[:board_id])
    @list = List.new
  end
  
  def create
  @board = Board.find(params[:board_id])
  @list = @board.lists.new(list_params)
  if @list.save
    redirect_to @board
  else
    render :new
  end
  end

  def edit
    @board = Board.find(params[:board_id])
    @list = @board.lists.find(params[:id])
  end

  def update
    @board = Board.find(params[:board_id])
    @list = @board.lists.find(params[:id])
    if @list.update(list_params)
      redirect_to @board
    else
      render :edit
    end
  end 

  def destroy
    @board = Board.find(params[:board_id])
    @list = @board.lists.find(params[:id])
    @list.destroy
    redirect_to @board
  end

private

  def list_params
    params.require(:list).permit(:name, :board_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :set_list, only: [:create,:update,:edit,:destroy, :new]
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to board_path(@list[:board_id])
    else
      render :new
    end
  end

  def edit
    @task = @list.tasks.find(params[:id])
  end

  def update
    @task = @list.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to board_path(@list[:board_id])
    else
      render :edit
    end
  end 

  def destroy
    @task = @list.tasks.find(params[:id])
    @task.destroy
    redirect_to board_path(@list[:board_id])
  end

  private
  
  def set_list
    @list= List.find(params[:list_id])
  end
  
  
  def task_params
    params.require(:task).permit(:body, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "input" %>
    </div>
    <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit <%=@board.name%></h1>
<%= render "form" %>

app/views/boards/index.html.erb
<h1>Boards</h1>
<hr />
<%= link_to "Add Board", new_board_path, class: "item" %>
<hr />
<% @boards.each do |board| %>
    <div>
        <h3><%= link_to board.name, board %></h3>
    </div>
<% end %>
 

app/views/boards/new.html.erb
<h1>Add Board</h1>
<%= render "form" %>

app/views/boards/show.html.erb
<h1><%=@board.name%></h1>
<%=link_to "Edit Board Name", edit_board_path(@board), class: 'huge ui button'%>
<%=link_to "Delete Board", @board, method: :delete, class: 'huge ui button'%>
<%=link_to 'New List', new_board_list_path(@board), class: 'huge ui button'%>  
<hr />
<ul>
    <% @lists.each do |list|%>
    <li>
        <%=list.name%> 
        <br />
        <%=link_to "Edit List Name", edit_board_list_path(@board, list), class: 'huge ui button' %>
        <%=link_to "Delete List", board_list_path(@board, list), method: :delete, class: 'huge ui button'%>
        <%=link_to "Add Task", new_list_task_path(list),class: 'huge ui button'%>
    </li>
    <br />
        <ul>
            <%list.tasks.each do |task| %>
            <li>
            Task Name: <%=task.name%> <br />
            Task Description: <%=task.body%> <br />
            <%=link_to "Edit Task", edit_list_task_path(list, task), class: 'huge ui button' %>
            <%=link_to "Delete Task", list_task_path(list, task), method: :delete, class: 'huge ui button'%>
            </li>
            <% end %>
        </ul>
        
    <% end %>
</ul>
 

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
    <%= link_to "Home", boards_path, class: "item" %>
    
   
        <% if current_user %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
        <% else %>
            <%link_to "Register", new_user_registration_path, class: "item" %>
            <%link_to "Login", new_user_session_path, class: "item" %>
        <% end %>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrollO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render "layouts/navbar" %>
   <div class='container'>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [@board, @list], local: true, class: "ui form") do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "input" %>
    </div>
    <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit <%=@list.name%> </h1>
<%=render "form"%>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
 <h1>Add List</h1>
<%= render "form" %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/tasks/_form.html.erb
<%= form_with(model: [@list, @task], local: true, class: "ui form") do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "input" %>
    </div>
    <div class="field">
        <%= f.label :body %>
        <%= f.text_field :body, class: "input"%>
    </div>
    <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%=render "form"%>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render "form" %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>